version: '3.8'

services:
  
  web:
    container_name: web
    build:
      dockerfile: ./Dockerfile
    entrypoint: ["./wait.sh"] # wait for the db service to start before this service is initialized
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - internal
  
  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'menuvoting'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - "db:/var/lib/mysql"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql" #initialize the menuvoting db if not exists
    networks:
      - internal

volumes:
  db:
    driver: local

networks: #by default the network exists but we are still giving it a custom name
  internal:
    name: network-internal
    driver: bridge