# Generated by Django 4.0.2 on 2022-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menutId', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=500)),
                ('menuDescription', models.CharField(max_length=500)),
                ('menuId', models.CharField(max_length=500)),
                ('menuDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantId', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantName', models.CharField(max_length=500)),
                ('restaurantAddress', models.CharField(max_length=500)),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('voteMenuId', models.IntegerField()),
                ('voteMenuDate', models.DateField()),
            ],
        ),
    ]
