# Generated by Django 4.0.2 on 2022-03-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0002_menu_restaurant_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
