# Generated by Django 4.0.2 on 2022-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0003_delete_customer_delete_orderdetail_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('OrderDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
            ],
        ),
    ]
