# Generated by Django 4.0.2 on 2022-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0005_delete_customer_delete_orderdetail_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuId',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurantId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
