# Generated by Django 4.0.2 on 2022-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0008_rename_menutid_menu_menuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menuId',
            new_name='menutId',
        ),
    ]
